name: Dulcet
options:
  bundleIdPrefix: com.legitimateapps.dulcet
  deploymentTarget:
    macOS: "14.0"
    iOS: "17.0"
    tvOS: "17.0"
settings:
  base:
    SWIFT_VERSION: "6.0"
    ARCHS: arm64
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    GENERATE_INFOPLIST_FILE: YES
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: 3LTL47SJ8C
    FRAMEWORK_SEARCH_PATHS: "$(inherited) $(BUILT_PRODUCTS_DIR)"
    OTHER_LDFLAGS: "$(inherited) -framework DulcetCore"
packages:
  DulcetKit:
    path: DulcetKit
targets:
  DulcetMac:
    type: application
    platform: macOS
    sources:
      - DulcetMac
    dependencies:
      - package: DulcetKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.legitimateapps.dulcet.dev
        PRODUCT_NAME: Dulcet DEV
    preBuildScripts:
      - name: Compile Kotlin Framework
        basedOnDependencyAnalysis: false
        script: |
          if [ "YES" = "$OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED" ]; then
            exit 0
          fi
          cd "$SRCROOT/.."
          ./gradlew :core:embedAndSignAppleFrameworkForXcode < /dev/null
  DulcetiOS:
    type: application
    platform: iOS
    sources:
      - DulcetiOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.legitimateapps.dulcet.dev
        PRODUCT_NAME: Dulcet DEV
        TARGETED_DEVICE_FAMILY: "1,2"
    preBuildScripts:
      - name: Compile Kotlin Framework
        basedOnDependencyAnalysis: false
        script: |
          if [ "YES" = "$OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED" ]; then
            exit 0
          fi
          cd "$SRCROOT/.."
          ./gradlew :core:embedAndSignAppleFrameworkForXcode < /dev/null
  DulcetTV:
    type: application
    platform: tvOS
    sources:
      - DulcetTV
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.legitimateapps.dulcet.dev
        PRODUCT_NAME: Dulcet DEV
    preBuildScripts:
      - name: Compile Kotlin Framework
        basedOnDependencyAnalysis: false
        script: |
          if [ "YES" = "$OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED" ]; then
            exit 0
          fi
          cd "$SRCROOT/.."
          ./gradlew :core:embedAndSignAppleFrameworkForXcode < /dev/null
