package com.legitimateapps.dulcet.core

/**
 * Language matching for the lyrics selection policy (§18.4). Pure, like the rest of the lyrics
 * model. A code is compared as a [LyricsLanguageTag]: a language key and a script.
 *
 * - **The key** is the primary subtag, lower-cased, with ISO 639-2 (bibliographic and terminology
 *   forms both) folded onto ISO 639-1 wherever ISO 639-1 has the language, so `ger`, `deu` and `de`
 *   are one language. A code no table knows is compared as written.
 * - **The script** is an explicit script subtag (`zh-Hant`), or the one a Chinese region implies
 *   (`zh-TW` is Traditional, `zh-CN` Simplified). Otherwise there is none.
 * - **A macrolanguage relates its members**: `no` with `nb` and `nn`, `zh` with `yue`, `ar` with
 *   `arb`. Related is a weaker match than the same language, never a mismatch.
 */
internal data class LyricsLanguageTag(val key: String, val script: String?)

/** Parses [code], or null when it names no language (`und`, `xxx`, blank, ...). */
internal fun lyricsLanguageTag(code: String): LyricsLanguageTag? {
    val key = lyricsLanguageKey(code) ?: return null
    var script: String? = null
    var region: String? = null
    for (subtag in code.trim().split('-', '_').drop(1)) {
        val lower = subtag.lowercase()
        when {
            script == null && region == null && lower.length == 4 && lower.all { it in 'a'..'z' } -> script = lower
            region == null && lower.length == 2 && lower.all { it in 'a'..'z' } -> region = lower
            region == null && lower.length == 3 && lower.all { it in '0'..'9' } -> region = lower
        }
    }
    return LyricsLanguageTag(key, script ?: impliedScript(key, region))
}

/**
 * How an [offered] layer language serves a [wanted] one. [related] is false for the same language
 * and true for a relative in its macrolanguage; the selection ranks every same-language match
 * ahead of every relative (§18.4 rule 3). [script] is 0 for the same script or neither side naming
 * one, 1 for one side naming one, 2 for two different scripts, lower being better: the same
 * language in another script is still the person's language, ahead of a relative in the right one.
 */
internal data class LyricsLanguageMatch(val related: Boolean, val script: Int)

/** How [offered] serves [wanted], or null when it does not serve it at all. */
internal fun lyricsLanguageMatch(wanted: LyricsLanguageTag, offered: LyricsLanguageTag): LyricsLanguageMatch? {
    val related = when {
        wanted.key == offered.key -> false
        macrolanguageOf(wanted.key) == macrolanguageOf(offered.key) -> true
        else -> return null
    }
    val script = when {
        wanted.script == offered.script -> 0
        wanted.script == null || offered.script == null -> 1
        else -> 2
    }
    return LyricsLanguageMatch(related, script)
}

private fun macrolanguageOf(key: String): String = MACROLANGUAGE_OF[key] ?: key

private fun impliedScript(key: String, region: String?): String? = when {
    key != "zh" || region == null -> null
    region in setOf("tw", "hk", "mo") -> "hant"
    region in setOf("cn", "sg", "my") -> "hans"
    else -> null
}

internal val UNSPECIFIED_LANGUAGE_CODES: Set<String> = setOf("und", "xxx", "zxx", "mul", "mis")

/**
 * Codes folded onto another before the tables apply. `cmn` (Mandarin) is keyed as `zh`, because
 * content tagged `zh` is Mandarin in practice (ASSUMED); `fil` (Filipino) as `tl` (Tagalog), which
 * Filipino is based on. `iw`, `in` and `ji` are ISO 639-1 codes withdrawn in favour of `he`, `id`
 * and `yi`, which `java.util.Locale.getLanguage()` still returned before JDK 17.
 */
internal val LYRICS_LANGUAGE_ALIASES: Map<String, String> = mapOf(
    "cmn" to "zh", "fil" to "tl", "iw" to "he", "in" to "id", "ji" to "yi",
)

/**
 * ISO 639-2 to ISO 639-1: every bibliographic and terminology code that has an ISO 639-1 code.
 * GENERATED by `tools/generate_lyrics_language_tables.py`, never hand-edited, from the Library of
 * Congress ISO 639-2 registration authority's code list,
 * https://www.loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt (retrieved 2026-09-24, sha256
 * 42b71885e4dc885559fda5ad059fd81838cf4782cedb5fd08cc3431f7d067371). Each pair is
 * `alpha3:alpha2`.
 */
internal val ISO_639_2_TO_1: Map<String, String> = pairTable(
    "aar:aa abk:ab afr:af aka:ak alb:sq amh:am ara:ar arg:an arm:hy asm:as ava:av ave:ae aym:ay " +
    "aze:az bak:ba bam:bm baq:eu bel:be ben:bn bis:bi bod:bo bos:bs bre:br bul:bg bur:my cat:ca " +
    "ces:cs cha:ch che:ce chi:zh chu:cu chv:cv cor:kw cos:co cre:cr cym:cy cze:cs dan:da deu:de " +
    "div:dv dut:nl dzo:dz ell:el eng:en epo:eo est:et eus:eu ewe:ee fao:fo fas:fa fij:fj fin:fi " +
    "fra:fr fre:fr fry:fy ful:ff geo:ka ger:de gla:gd gle:ga glg:gl glv:gv gre:el grn:gn guj:gu " +
    "hat:ht hau:ha heb:he her:hz hin:hi hmo:ho hrv:hr hun:hu hye:hy ibo:ig ice:is ido:io iii:ii " +
    "iku:iu ile:ie ina:ia ind:id ipk:ik isl:is ita:it jav:jv jpn:ja kal:kl kan:kn kas:ks kat:ka " +
    "kau:kr kaz:kk khm:km kik:ki kin:rw kir:ky kom:kv kon:kg kor:ko kua:kj kur:ku lao:lo lat:la " +
    "lav:lv lim:li lin:ln lit:lt ltz:lb lub:lu lug:lg mac:mk mah:mh mal:ml mao:mi mar:mr may:ms " +
    "mkd:mk mlg:mg mlt:mt mon:mn mri:mi msa:ms mya:my nau:na nav:nv nbl:nr nde:nd ndo:ng nep:ne " +
    "nld:nl nno:nn nob:nb nor:no nya:ny oci:oc oji:oj ori:or orm:om oss:os pan:pa per:fa pli:pi " +
    "pol:pl por:pt pus:ps que:qu roh:rm ron:ro rum:ro run:rn rus:ru sag:sg san:sa sin:si slk:sk " +
    "slo:sk slv:sl sme:se smo:sm sna:sn snd:sd som:so sot:st spa:es sqi:sq srd:sc srp:sr ssw:ss " +
    "sun:su swa:sw swe:sv tah:ty tam:ta tat:tt tel:te tgk:tg tgl:tl tha:th tib:bo tir:ti ton:to " +
    "tsn:tn tso:ts tuk:tk tur:tr twi:tw uig:ug ukr:uk urd:ur uzb:uz ven:ve vie:vi vol:vo wel:cy " +
    "wln:wa wol:wo xho:xh yid:yi yor:yo zha:za zho:zh zul:zu",
)

/**
 * Each active individual language to its macrolanguage, both as keys (ISO 639-1 where it exists).
 * GENERATED by `tools/generate_lyrics_language_tables.py`, never hand-edited, from the ISO 639-3
 * registration authority's macrolanguage mappings,
 * https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3-macrolanguages.tab (retrieved
 * 2026-09-24, sha256 fb01a86376d9c1abfc96d16be1b6dcffb4776a1f52fa22338d4979e9ffe1822f), keeping
 * rows with status `A`, after [LYRICS_LANGUAGE_ALIASES] and [ISO_639_2_TO_1]; `cmn` is therefore
 * absent, being `zh` itself. Each pair is `member:macrolanguage`.
 */
internal val MACROLANGUAGE_OF: Map<String, String> = pairTable(
    "aae:sq aao:ar aat:sq abh:ar abv:ar acm:ar acq:ar acw:ar acx:ar acy:ar adf:ar aeb:ar aec:ar " +
    "afb:ar aii:syr aju:jrb aln:sq als:sq apc:ar apd:ar arb:ar arq:ar ars:ar ary:ar arz:ar auz:ar " +
    "avl:ar ayc:ay ayh:ar ayl:ar ayn:ar ayp:ar ayr:ay azb:az azj:az bcc:bal bcl:bik bdt:gba " +
    "bgn:bal bgp:bal bgq:raj bhr:mg bjn:ms bln:bik bmm:mg bs:hbs btj:ms bto:bik bve:ms bvu:ms " +
    "bxk:luy bxm:bua bxr:bua bxu:bua bzc:mg cdo:zh ciw:oj cjy:zh ckb:ku cld:syr cls:sa cnp:zh " +
    "cnr:hbs coa:ms cpx:zh cqd:hmn crj:cr crk:cr crl:cr crm:cr csp:zh csw:cr cts:bik cwd:cr " +
    "czh:zh czo:zh dgo:doi dhd:mwr dib:din dik:din dip:din diq:zza diw:din dks:din dty:ne dup:ms " +
    "ebk:bnc ekk:et emk:man enb:kln esg:gon esi:ik esk:ik eyo:kln fat:ak fbl:bik ffm:ff fub:ff " +
    "fuc:ff fue:ff fuf:ff fuh:ff fui:ff fuq:ff fuv:ff gan:zh gax:om gaz:om gbo:grb gbp:gba " +
    "gbq:gba gda:raj gec:grb gju:raj gkp:kpe gmm:gba gno:gon gnw:gn gom:kok grj:grb grv:grb " +
    "gry:grb gso:gba gug:gn gui:gn gun:gn gya:gba hae:om hak:zh hax:hai hdn:hai hea:hmn hji:ms " +
    "hma:hmn hmc:hmn hmd:hmn hme:hmn hmg:hmn hmh:hmn hmi:hmn hmj:hmn hml:hmn hmm:hmn hmp:hmn " +
    "hmq:hmn hms:hmn hmw:hmn hmy:hmn hmz:hmn hnd:lah hnj:hmn hnm:zh hno:lah hoj:raj hr:hbs " +
    "hrm:hmn hsn:zh huj:hmn id:ms ida:luy ike:iu ikt:iu jak:ms jat:lah jax:ms jye:jrb kby:kr " +
    "khk:mn kiu:zza kmr:ku knc:kr kng:kg knn:kok koi:kv kpv:kv krt:kr kvb:ms kvr:ms kwy:kg kxd:ms " +
    "lbk:bnc lbl:bik lce:ms lcf:ms ldi:kg liw:ms lkb:luy lko:luy lks:luy lri:luy lrm:luy lsm:luy " +
    "ltg:lv lto:luy lts:luy luh:zh lvs:lv lwg:luy lzh:zh max:ms meo:ms mfa:ms mfb:ms mhr:chm " +
    "min:ms mku:man mlq:man mmr:hmn mnk:man mnp:zh mqg:ms mrj:chm msc:man msh:mg msi:ms mtr:mwr " +
    "mui:ms mup:raj muq:hmn mve:mwr mvf:mn mwk:man mww:hmn nan:zh nb:no nhd:gn niq:kln nle:luy " +
    "nn:no npi:ne nyd:luy obk:bnc ojb:oj ojc:oj ojg:oj ojs:oj ojw:oj oki:kln orc:om orn:ms ors:ms " +
    "ory:or otw:oj pbt:ps pbu:ps pel:ms pes:fa pga:ar phr:lah pko:kln plt:mg pnb:lah prs:fa " +
    "pse:ms pst:ps qub:qu qud:qu quf:qu qug:qu quh:qu quk:qu qul:qu qup:qu qur:qu qus:qu quw:qu " +
    "qux:qu quy:qu quz:qu qva:qu qvc:qu qve:qu qvh:qu qvi:qu qvj:qu qvl:qu qvm:qu qvn:qu qvo:qu " +
    "qvp:qu qvs:qu qvw:qu qvz:qu qwa:qu qwc:qu qwh:qu qws:qu qxa:qu qxc:qu qxh:qu qxl:qu qxn:qu " +
    "qxo:qu qxp:qu qxr:qu qxt:qu qxu:qu qxw:qu rag:luy rbk:bnc rbl:bik rmc:rom rmf:rom rml:rom " +
    "rmn:rom rmo:rom rmw:rom rmy:rom rwr:mwr scs:den sdc:sc sdh:ku sdn:sc sfm:hmn sgc:kln shu:ar " +
    "sjc:zh skg:mg skr:lah spv:or spy:kln sr:hbs src:sc sro:sc ssh:ar swc:sw swh:sw swv:mwr " +
    "taq:tmh tdx:mg tec:kln thv:tmh thz:tmh tkg:mg tmw:ms ttq:tmh tuy:kln tw:ak txy:mg ubl:bik " +
    "umu:del unm:del urk:ms uzn:uz uzs:uz vbk:bnc vkk:ms vkt:ms vro:et vsn:sa wbr:raj wry:mwr " +
    "wsg:gon wuu:zh xhe:lah xmm:ms xmv:mg xmw:mg xnr:doi xpe:kpe xsl:den ydd:yi yhd:jrb yih:yi " +
    "yud:jrb yue:zh zaa:zap zab:zap zac:zap zad:zap zae:zap zaf:zap zai:zap zam:zap zao:zap " +
    "zaq:zap zar:zap zas:zap zat:zap zav:zap zaw:zap zax:zap zca:zap zcd:zap zch:za zeh:za zgb:za " +
    "zgm:za zgn:za zhd:za zhn:za zlj:za zlm:ms zln:za zlq:za zmi:ms zoo:zap zpa:zap zpb:zap " +
    "zpc:zap zpd:zap zpe:zap zpf:zap zpg:zap zph:zap zpi:zap zpj:zap zpk:zap zpl:zap zpm:zap " +
    "zpn:zap zpo:zap zpp:zap zpq:zap zpr:zap zps:zap zpt:zap zpu:zap zpv:zap zpw:zap zpx:zap " +
    "zpy:zap zpz:zap zqe:za zsm:ms zsr:zap zte:zap ztg:zap ztl:zap ztm:zap ztn:zap ztp:zap " +
    "ztq:zap zts:zap ztt:zap ztu:zap ztx:zap zty:zap zyb:za zyg:za zyj:za zyn:za zzj:za",
)

private fun pairTable(pairs: String): Map<String, String> =
    pairs.split(' ').associate { it.substringBefore(':') to it.substringAfter(':') }
